import type { ThemeConfig } from "antd";

export const modernTheme: ThemeConfig = {
  token: {
    colorPrimary: "#176b87",
    colorSuccess: "#17815f",
    colorWarning: "#b7791f",
    colorError: "#c2413a",
    colorInfo: "#176b87",
    fontFamily: `"Inter","SF Pro Text","Segoe UI","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif`,
    fontSize: 14,
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: "0 8px 24px rgba(15, 23, 42, 0.07), 0 1px 3px rgba(15, 23, 42, 0.05)",
    boxShadowSecondary: "0 16px 42px rgba(15, 23, 42, 0.12), 0 4px 12px rgba(15, 23, 42, 0.07)",
    padding: 16,
    margin: 16,
    colorBgContainer: "#fbfcfd",
    colorBgElevated: "#ffffff",
    colorBgLayout: "#eef2f5",
    colorBorder: "#d7dee6",
    colorBorderSecondary: "#e8edf2",
    colorText: "#17202a",
    colorTextSecondary: "rgba(23, 32, 42, 0.66)",
    colorTextTertiary: "rgba(23, 32, 42, 0.46)",
    colorTextQuaternary: "rgba(23, 32, 42, 0.28)",
    colorLink: "#176b87",
    colorLinkHover: "#12566e",
    colorLinkActive: "#0f4153",
  },
  components: {
    Button: {
      controlHeight: 36,
      controlHeightLG: 42,
      controlHeightSM: 30,
      fontWeight: 600,
      borderRadius: 6,
      primaryShadow: "0 4px 12px rgba(23, 107, 135, 0.22)",
      defaultBg: "#fbfcfd",
      defaultBorderColor: "#d7dee6",
      defaultColor: "#17202a",
    },
    Input: {
      controlHeight: 36,
      controlHeightLG: 42,
      controlHeightSM: 30,
      paddingBlock: 8,
      paddingBlockLG: 10,
      paddingBlockSM: 6,
      activeBorderColor: "#176b87",
      hoverBorderColor: "#176b87",
      colorBgContainer: "#fbfcfd",
    },
    Select: {
      controlHeight: 36,
      controlHeightLG: 42,
      controlHeightSM: 30,
      colorBgContainer: "#fbfcfd",
    },
    Card: {
      borderRadiusLG: 8,
      paddingLG: 24,
    },
    Modal: {
      borderRadiusLG: 10,
    },
    Message: {
      contentBg: "#ffffff",
      contentPadding: "10px 16px",
    },
    Tag: {
      borderRadiusSM: 4,
    },
    Layout: {
      headerBg: "#fbfcfd",
      headerHeight: 64,
      headerPadding: "0 24px",
      siderBg: "transparent",
      bodyBg: "#eef2f5",
    },
    Table: {
      borderColor: "#e8edf2",
      headerBg: "#f5f8fa",
      headerColor: "rgba(23, 32, 42, 0.58)",
      rowHoverBg: "#f3f8f9",
    },
    Tabs: {
      itemSelectedColor: "#176b87",
      inkBarColor: "#176b87",
    },
    Pagination: {
      itemActiveBg: "#176b87",
      colorPrimary: "#176b87",
      colorPrimaryHover: "#12566e",
    },
  },
};
export const whatsappTheme: ThemeConfig = {
  token: {
    colorPrimary: "#25D366",
    colorSuccess: "#25D366",
    colorBgContainer: "#FFFFFF",
    colorBgLayout: "#F0F2F5",
    borderRadius: 8,
    fontFamily: `"IBM Plex Sans","PingFang SC","Hiragino Sans GB","Microsoft YaHei","Segoe UI",sans-serif`,
  },
  components: {
    Layout: {
      headerBg: "#FFFFFF",
      siderBg: "#FFFFFF",
      bodyBg: "#F0F2F5",
    },
  },
};
