import type { ThemeConfig } from "antd";

export const modernTheme: ThemeConfig = {
  token: {
    colorPrimary: "#1657c1",
    colorSuccess: "#12a06d",
    colorWarning: "#d97706",
    colorError: "#dc2626",
    colorInfo: "#1657c1",
    fontFamily: `"Inter","SF Pro Text","Segoe UI","PingFang SC","Hiragino Sans GB","Microsoft YaHei",sans-serif`,
    fontSize: 14,
    borderRadius: 6,
    borderRadiusLG: 8,
    borderRadiusSM: 4,
    boxShadow: "0 4px 16px rgba(10, 18, 40, 0.08), 0 1px 4px rgba(10, 18, 40, 0.04)",
    boxShadowSecondary: "0 8px 32px rgba(10, 18, 40, 0.12), 0 2px 8px rgba(10, 18, 40, 0.06)",
    padding: 16,
    margin: 16,
    colorBgContainer: "#ffffff",
    colorBgElevated: "#ffffff",
    colorBgLayout: "#f0f3f8",
    colorBorder: "#dce1ea",
    colorBorderSecondary: "#eaecf2",
    colorText: "#111827",
    colorTextSecondary: "rgba(17, 24, 39, 0.64)",
    colorTextTertiary: "rgba(17, 24, 39, 0.46)",
    colorTextQuaternary: "rgba(17, 24, 39, 0.3)",
    colorLink: "#1657c1",
    colorLinkHover: "#1248a0",
    colorLinkActive: "#0d3880",
  },
  components: {
    Button: {
      controlHeight: 36,
      controlHeightLG: 42,
      controlHeightSM: 30,
      fontWeight: 600,
      borderRadius: 6,
      primaryShadow: "0 2px 8px rgba(22, 87, 193, 0.24)",
      defaultBg: "#ffffff",
      defaultBorderColor: "#dce1ea",
      defaultColor: "#111827",
    },
    Input: {
      controlHeight: 36,
      controlHeightLG: 42,
      controlHeightSM: 30,
      paddingBlock: 8,
      paddingBlockLG: 10,
      paddingBlockSM: 6,
      activeBorderColor: "#1657c1",
      hoverBorderColor: "#1657c1",
      colorBgContainer: "#ffffff",
    },
    Select: {
      controlHeight: 36,
      controlHeightLG: 42,
      controlHeightSM: 30,
      colorBgContainer: "#ffffff",
    },
    Card: {
      borderRadiusLG: 8,
      paddingLG: 24,
    },
    Modal: {
      borderRadiusLG: 10,
    },
    Message: {
      contentBg: "#ffffff",
      contentPadding: "10px 16px",
    },
    Tag: {
      borderRadiusSM: 4,
    },
    Layout: {
      headerBg: "#f0f3f8",
      headerHeight: 64,
      headerPadding: "0 24px",
      siderBg: "transparent",
      bodyBg: "#f0f3f8",
    },
    Table: {
      borderColor: "#eaecf2",
      headerBg: "#f6f8fb",
      headerColor: "rgba(17, 24, 39, 0.56)",
      rowHoverBg: "#f6f8fb",
    },
    Tabs: {
      itemSelectedColor: "#1657c1",
      inkBarColor: "#1657c1",
    },
    Pagination: {
      itemActiveBg: "#1657c1",
      colorPrimary: "#1657c1",
      colorPrimaryHover: "#1248a0",
    },
  },
};
export const whatsappTheme: ThemeConfig = {
  token: {
    colorPrimary: "#25D366",
    colorSuccess: "#25D366",
    colorBgContainer: "#FFFFFF",
    colorBgLayout: "#F0F2F5",
    borderRadius: 8,
    fontFamily: `"IBM Plex Sans","PingFang SC","Hiragino Sans GB","Microsoft YaHei","Segoe UI",sans-serif`,
  },
  components: {
    Layout: {
      headerBg: "#FFFFFF",
      siderBg: "#FFFFFF",
      bodyBg: "#F0F2F5",
    },
  },
};
